% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Dec-2024 18:12:39
%  MATLAB version: 23.2.0.2459199 (R2023b) Update 5
% -------------------------------------------------------------------
                                                 

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [0 0 0];
smiData.RigidTransform(1).angle = 1.5707963267948968;
smiData.RigidTransform(1).axis = [1.1102230246251562E-16 -1 1.1102230246251562E-16 ...
                                  ];
smiData.RigidTransform(1).ID = 'B[eje:1:-:eslabon:1]';
smiData.RigidTransform(1).ID = convertCharsToStrings( ...
  smiData.RigidTransform(1).ID);
smiData.RigidTransform(2).translation = ...
  [0 4.8214440911313115E-17 -8.7419135797256388E-17];
smiData.RigidTransform(2).angle = 1.5707963267948968;
smiData.RigidTransform(2).axis = [-5.5511151231257963E-17 -1 -5.5511151231257963E-17 ...
                                  ];
smiData.RigidTransform(2).ID = 'F[eje:1:-:eslabon:1]';
smiData.RigidTransform(2).ID = convertCharsToStrings( ...
  smiData.RigidTransform(2).ID);
smiData.RigidTransform(3).translation = ...
  [0.39370078740157693 -2.1854783949314106E-15 -9.8425196850393721];
smiData.RigidTransform(3).angle = 2.0943951023931957;
smiData.RigidTransform(3).axis = [-0.57735026918962584 -0.57735026918962573 ...
                                  0.57735026918962573];
smiData.RigidTransform(3).ID = 'B[eslabon:1:-:eslabon:2]';
smiData.RigidTransform(3).ID = convertCharsToStrings( ...
  smiData.RigidTransform(3).ID);
smiData.RigidTransform(4).translation = ...
  [0 4.8214440911313115E-17 -8.7419135797256388E-17];
smiData.RigidTransform(4).angle = 2.0943951023931957;
smiData.RigidTransform(4).axis = [0.57735026918962573 -0.57735026918962584 ...
                                  -0.57735026918962573];
smiData.RigidTransform(4).ID = 'F[eslabon:1:-:eslabon:2]';
smiData.RigidTransform(4).ID = convertCharsToStrings( ...
  smiData.RigidTransform(4).ID);
smiData.RigidTransform(5).translation = ...
  [-2.9674991371812105 2.6225740739176924E-16 -0.21741371721542513];
smiData.RigidTransform(5).angle = 0;
smiData.RigidTransform(5).axis = [0 0 0];
smiData.RigidTransform(5).ID = 'RootGround[eje:1]';
smiData.RigidTransform(5).ID = convertCharsToStrings( ...
  smiData.RigidTransform(5).ID);
smiData.Solid = struct;
smiData.Solid(1).mass = 0.019634954084935367;
smiData.Solid(1).CoM = [-4.9999999999999991 0 -5.2283872406459785E-9];
smiData.Solid(1).MoI = [6.1359227553231053 3.2315855988168281 3.2315863912552021 ...
                        ];
smiData.Solid(1).PoI = [0 0 0];
smiData.Solid(1).color = [0.74901960784313726 0.74901960784313726 0.74901960784313726 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'eje.ipt_{85F9C506-4F78-7F45-6B2E-7F91A8524D46}';
smiData.Solid(1).ID = convertCharsToStrings(smiData.Solid(1).ID);
smiData.Solid(2).mass = 0.14463495408493626;
smiData.Solid(2).CoM = [5.0000000000000266 -1.1790390342453519E-14 -125.00000000000003 ...
                        ];
smiData.Solid(2).MoI = [1042.0987473953355 1014.1944104369388 30.314919526479123 ...
                        ];
smiData.Solid(2).PoI = [2.1316282072803013E-13 1.9326762412674727E-13 0 ...
                        ];
smiData.Solid(2).color = [0.74901960784313726 0.74901960784313726 0.74901960784313726 ...
                          ];
smiData.Solid(2).opacity = 1;
smiData.Solid(2).ID = ['eslabon.ipt_{1C33B10B-4B83-8815-3659-2FB5B665B9' ...
                       '74}'];
smiData.Solid(2).ID = convertCharsToStrings(smiData.Solid(2).ID);
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = -6.5559993560782567E-16;
smiData.RevoluteJoint(1).ID = '[eje:1:-:eslabon:1]';
smiData.RevoluteJoint(1).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(1).ID);
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 179.99999999999997;
smiData.RevoluteJoint(2).ID = '[eslabon:1:-:eslabon:2]';
smiData.RevoluteJoint(2).ID = convertCharsToStrings( ...
  smiData.RevoluteJoint(2).ID);

